// src/lessons.ts
import { Module } from './types';

export const MODULES: Module[] = [
  {
    id: 1,
    title: 'Crypto History',
    emoji: '₿',
    color: '#F7931A',
    xp: 100,
    difficulty: 'Beginner',
    timeMin: 5,
    description: 'The origin of blockchain and Bitcoin',
    steps: [
      {
        type: 'info',
        icon: '₿',
        text: 'In 2008, an anonymous person (or group) called Satoshi Nakamoto published the Bitcoin whitepaper. It described a system for peer-to-peer electronic cash — no banks needed.',
      },
      {
        type: 'info',
        icon: '⛓️',
        text: 'A blockchain is a chain of blocks — each block contains a batch of transactions. Once written, blocks cannot be changed. This makes it tamper-proof and transparent.',
      },
      {
        type: 'info',
        icon: '🌍',
        text: 'The Bitcoin network is maintained by thousands of nodes worldwide. No single company or government controls it. This is called decentralization.',
      },
      {
        type: 'quiz',
        question: 'What is the main problem Bitcoin was designed to solve?',
        options: ['Making transactions faster', 'Removing the need for trusted third parties like banks', 'Creating digital art', 'Replacing credit cards'],
        correct: 1,
        explanation: 'Bitcoin enables trustless peer-to-peer transactions without intermediaries.',
      },
      {
        type: 'quiz',
        question: 'What is the maximum supply of Bitcoin?',
        options: ['1 million BTC', '10 million BTC', '21 million BTC', 'Unlimited'],
        correct: 2,
        explanation: 'Bitcoin has a hard cap of 21 million coins, making it deflationary by design.',
      },
      {
        type: 'quiz',
        question: 'What is a "block" in a blockchain?',
        options: ['A failed transaction', 'A batch of verified transactions stored permanently', 'A type of wallet', 'A smart contract'],
        correct: 1,
        explanation: 'Blocks contain groups of transactions that are verified and added to the chain.',
      },
      {
        type: 'quiz',
        question: 'What is the double-spend problem that Bitcoin solved?',
        options: ['Spending twice as much money', 'Using the same digital coin twice without a central authority detecting it', 'Paying double fees', 'Having two wallets'],
        correct: 1,
        explanation: 'Before Bitcoin, digital money could be copied and spent twice. Blockchain solves this.',
      },
      {
        type: 'quiz',
        question: 'What is Proof of Work (PoW)?',
        options: ['A way to prove you own a wallet', 'A consensus mechanism where miners solve complex puzzles to add blocks', 'A type of staking', 'A legal document'],
        correct: 1,
        explanation: 'PoW requires miners to use computational power to validate transactions — energy-intensive but secure.',
      },
      {
        type: 'quiz',
        question: 'Why can\'t you change a transaction once it\'s on the blockchain?',
        options: ['The government prevents it', 'Each block contains a hash of the previous block — changing one breaks the entire chain', 'You need a password', 'Transactions auto-lock after 1 minute'],
        correct: 1,
        explanation: 'Cryptographic hashing links all blocks together, making historical data immutable.',
      },
      {
        type: 'quiz',
        question: 'What is a "51% attack"?',
        options: ['Hacking 51 wallets at once', 'When one entity controls >50% of network hash power and can manipulate the chain', 'A phishing scam', 'A type of token burn'],
        correct: 1,
        explanation: 'Controlling majority hash power allows rewriting recent transactions — the main attack vector on PoW chains.',
      },
    ],
  },
  {
    id: 2,
    title: 'What is Solana?',
    emoji: '⚡',
    color: '#9945FF',
    xp: 100,
    difficulty: 'Beginner',
    timeMin: 5,
    description: 'Fastest blockchain in the world',
    steps: [
      {
        type: 'info',
        icon: '⚡',
        text: 'Solana was founded by Anatoly Yakovenko in 2017 and launched in 2020. It can process 65,000+ transactions per second — compared to Bitcoin\'s 7 TPS and Ethereum\'s 30 TPS.',
      },
      {
        type: 'info',
        icon: '⏰',
        text: 'Solana\'s secret weapon is Proof of History (PoH) — a cryptographic clock that timestamps every transaction before it\'s added to the chain. This removes the need for validators to communicate timing, massively speeding up consensus.',
      },
      {
        type: 'info',
        icon: '💸',
        text: 'Transaction fees on Solana cost less than $0.001. Compare that to Ethereum where a single swap can cost $50+ in gas fees. Low fees make Solana ideal for DeFi, NFTs, and everyday use.',
      },
      {
        type: 'quiz',
        question: 'What is Proof of History (PoH)?',
        options: ['A way to mine tokens', 'A cryptographic clock that timestamps transactions before consensus', 'A staking mechanism', 'A type of NFT standard'],
        correct: 1,
        explanation: 'PoH is Solana\'s unique innovation — it proves the order of events without validators needing to agree on time.',
      },
      {
        type: 'quiz',
        question: 'How does Solana achieve parallel transaction processing?',
        options: ['It uses multiple blockchains', 'Sealevel runtime processes non-overlapping transactions simultaneously', 'It skips validation', 'It uses GPUs for mining'],
        correct: 1,
        explanation: 'Sealevel is Solana\'s parallel smart contract runtime — transactions that don\'t touch the same state run at the same time.',
      },
      {
        type: 'quiz',
        question: 'What is a Solana validator?',
        options: ['A user who validates their email', 'A node that verifies transactions and maintains the ledger', 'A type of token', 'An exchange'],
        correct: 1,
        explanation: 'Validators stake SOL, process transactions, and earn rewards for securing the network.',
      },
      {
        type: 'quiz',
        question: 'What is the Solana "turbine" protocol?',
        options: ['An energy generator', 'A block propagation protocol that breaks data into packets for fast distribution', 'A DeFi product', 'A wallet feature'],
        correct: 1,
        explanation: 'Turbine splits block data into small packets, allowing fast distribution across the validator network.',
      },
      {
        type: 'quiz',
        question: 'What happens during a Solana network outage?',
        options: ['All tokens are lost', 'Validators restart the network via a coordinated restart process', 'The blockchain resets to zero', 'Solana shuts down permanently'],
        correct: 1,
        explanation: 'Solana has experienced outages where validators coordinate an off-chain restart — a known tradeoff for its performance architecture.',
      },
      {
        type: 'quiz',
        question: 'What is "rent" on Solana?',
        options: ['Monthly fee to use the blockchain', 'A small SOL deposit required to store data on-chain, refundable when account is closed', 'Tax on transactions', 'Validator fee'],
        correct: 1,
        explanation: 'Solana charges rent to store state on-chain. Keeping 2+ years of rent exempt in an account is common practice.',
      },
      {
        type: 'quiz',
        question: 'What is the role of the Solana Foundation?',
        options: ['To control all transactions', 'To support ecosystem development, grants, and validator decentralization', 'To run the only nodes', 'To issue all tokens'],
        correct: 1,
        explanation: 'The Solana Foundation is a non-profit supporting the ecosystem but does not control the protocol.',
      },
    ],
  },
  {
    id: 3,
    title: 'Wallet Security',
    emoji: '🔐',
    color: '#14F195',
    xp: 200,
    difficulty: 'Intermediate',
    timeMin: 15,
    description: 'Protect your seed phrase and assets',
    steps: [
      {
        type: 'info',
        icon: '🔑',
        text: 'Your seed phrase (12 or 24 words) is the master key to your wallet. Anyone with these words can access ALL your funds — forever. Write it on paper, store it offline, never digitally.',
      },
      {
        type: 'info',
        icon: '🛡️',
        text: 'The Seeker Seed Vault stores your private keys in a secure hardware enclave on your phone. Even if someone steals your phone, they can\'t access your keys without your biometrics.',
      },
      {
        type: 'info',
        icon: '🚨',
        text: 'Legitimate apps and support teams will NEVER ask for your seed phrase. If anyone asks — it is 100% a scam. Disconnect and report immediately.',
      },
      {
        type: 'quiz',
        question: 'What is the difference between a public key and a private key?',
        options: ['They are the same thing', 'Public key is your wallet address (shareable); private key signs transactions (never share)', 'Public key unlocks your wallet', 'Private key is your username'],
        correct: 1,
        explanation: 'Your public key is like your IBAN — safe to share. Your private key is like your PIN — never share it.',
      },
      {
        type: 'quiz',
        question: 'You receive an email from "Phantom Support" asking for your seed phrase to fix an issue. What do you do?',
        options: ['Provide it — they need it to help you', 'Ignore and delete — no legitimate service ever asks for your seed phrase', 'Send half the words', 'Call them back'],
        correct: 1,
        explanation: 'This is a classic social engineering phishing attack. No legitimate service ever needs your seed phrase.',
      },
      {
        type: 'quiz',
        question: 'What is a hardware wallet?',
        options: ['A physical crypto ATM', 'A dedicated device that stores private keys offline and signs transactions without exposing keys', 'A mobile wallet app', 'A paper wallet'],
        correct: 1,
        explanation: 'Hardware wallets like Ledger keep keys air-gapped — transactions are signed on the device, keys never leave.',
      },
      {
        type: 'quiz',
        question: 'What is a "revoke approval" and when should you use it?',
        options: ['Canceling a pending transaction', 'Removing a dApp\'s permission to spend your tokens — do this if you no longer trust a protocol', 'Deleting your wallet', 'Unstaking SOL'],
        correct: 1,
        explanation: 'Token approvals let dApps spend your tokens. Unused approvals are a security risk — revoke them regularly.',
      },
      {
        type: 'quiz',
        question: 'What is the safest way to store your seed phrase?',
        options: ['Screenshot on your phone', 'Password manager', 'Written on paper or metal, stored offline in a secure location', 'Email draft'],
        correct: 2,
        explanation: 'Digital storage is always vulnerable to hacks. Physical offline storage is the gold standard.',
      },
      {
        type: 'quiz',
        question: 'What is a "blind signing" risk?',
        options: ['Signing with your eyes closed', 'Approving a transaction without being able to read what it does — can drain your wallet', 'A type of NFT mint', 'Two-factor authentication'],
        correct: 1,
        explanation: 'Some dApps show unreadable transaction data. Never sign what you don\'t understand.',
      },
      {
        type: 'quiz',
        question: 'What does the Seeker Seed Vault use to protect your keys?',
        options: ['Cloud encryption', 'A hardware security enclave + biometric authentication', 'Password only', 'PIN code only'],
        correct: 1,
        explanation: 'The Seed Vault combines hardware-level security with biometrics — significantly stronger than software wallets.',
      },
    ],
  },
  {
    id: 4,
    title: 'Tokens: SOL, USDC, SKR',
    emoji: '🪙',
    color: '#FFD700',
    xp: 150,
    difficulty: 'Beginner',
    timeMin: 8,
    description: 'Understanding different tokens on Solana',
    steps: [
      {
        type: 'info',
        icon: '🪙',
        text: 'Solana has two types of assets: SOL (the native coin used for fees and staking) and SPL tokens (custom tokens built on Solana, like USDC, BONK, JTO, SKR).',
      },
      {
        type: 'info',
        icon: '💵',
        text: 'USDC is a stablecoin — always worth $1. It\'s backed by real USD reserves held by Circle. Perfect for holding value without price volatility.',
      },
      {
        type: 'info',
        icon: '📱',
        text: 'SKR is the Seeker ecosystem token. It\'s used for staking to Guardian nodes, accessing premium features, and participating in the Seeker network economy.',
      },
      {
        type: 'quiz',
        question: 'What is the SPL token standard?',
        options: ['Solana\'s equivalent of Ethereum\'s ERC-20 — the standard for creating tokens on Solana', 'A type of NFT', 'A hardware wallet standard', 'A DeFi protocol'],
        correct: 0,
        explanation: 'SPL (Solana Program Library) is the token standard on Solana, like ERC-20 on Ethereum.',
      },
      {
        type: 'quiz',
        question: 'What is Token-2022 (Token Extensions)?',
        options: ['A new Solana version', 'An upgraded token standard with features like transfer fees, confidential transfers, and more', 'A meme token', 'A wallet upgrade'],
        correct: 1,
        explanation: 'Token-2022 extends the SPL standard with powerful new features — SKR uses this standard.',
      },
      {
        type: 'quiz',
        question: 'Why do you need SOL even when transacting with USDC?',
        options: ['You don\'t — USDC pays its own fees', 'SOL is required for all network fees regardless of which token you\'re sending', 'USDC automatically converts', 'Only on Ethereum'],
        correct: 1,
        explanation: 'All Solana transactions pay fees in SOL. Always keep a small SOL balance for gas.',
      },
      {
        type: 'quiz',
        question: 'What is a token mint address?',
        options: ['Where physical coins are made', 'The unique on-chain identifier for a specific token — used to verify authenticity', 'Your wallet address', 'A DeFi pool'],
        correct: 1,
        explanation: 'Always verify a token\'s mint address to avoid fake tokens with similar names.',
      },
      {
        type: 'quiz',
        question: 'What is token "burning"?',
        options: ['Sending tokens to a hacker', 'Permanently removing tokens from supply by sending to an unspendable address', 'Staking tokens', 'Converting to SOL'],
        correct: 1,
        explanation: 'Burning reduces circulating supply — often used to create deflationary tokenomics.',
      },
      {
        type: 'quiz',
        question: 'What backs USDC\'s $1 peg?',
        options: ['Bitcoin reserves', 'US Dollar cash and short-term US treasuries held by Circle', 'Algorithmic supply control', 'Gold'],
        correct: 1,
        explanation: 'Unlike algorithmic stablecoins (which have failed), USDC is fully collateralized with real dollars.',
      },
      {
        type: 'quiz',
        question: 'What is the risk of an algorithmic stablecoin vs USDC?',
        options: ['No difference', 'Algorithmic stablecoins can lose their peg and collapse to zero (e.g. UST/Luna 2022)', 'USDC is riskier', 'Algorithmic ones are safer'],
        correct: 1,
        explanation: 'The UST/Luna collapse in 2022 wiped out $40B+ showing algorithmic stablecoins carry extreme depeg risk.',
      },
    ],
  },
  {
    id: 5,
    title: 'How Swapping Works',
    emoji: '🔄',
    color: '#00D4FF',
    xp: 150,
    difficulty: 'Beginner',
    timeMin: 8,
    description: 'Trade tokens instantly via Jupiter',
    steps: [
      {
        type: 'info',
        icon: '🔄',
        text: 'A DEX (Decentralized Exchange) lets you swap tokens without a central company. No account needed, no KYC — just connect your wallet and trade.',
      },
      {
        type: 'info',
        icon: '🪐',
        text: 'Jupiter is Solana\'s leading swap aggregator. It scans all DEXs (Raydium, Orca, Meteora, etc.) and routes your swap through the best path for the lowest price impact.',
      },
      {
        type: 'info',
        icon: '📊',
        text: 'Key concepts: Slippage = how much price can move before your swap fails. Price impact = how much your trade moves the market. For large trades, high price impact means you\'re moving the price against yourself.',
      },
      {
        type: 'quiz',
        question: 'What is an AMM (Automated Market Maker)?',
        options: ['A robot trader', 'A smart contract that uses a mathematical formula (x*y=k) to price tokens and enable trades without order books', 'An exchange company', 'A type of wallet'],
        correct: 1,
        explanation: 'AMMs replaced traditional order books with liquidity pools and a pricing formula — enabling permissionless trading.',
      },
      {
        type: 'quiz',
        question: 'What does "slippage tolerance" mean?',
        options: ['How much your wallet can hold', 'The maximum price difference you\'ll accept between quote and execution', 'Transaction speed', 'Fee percentage'],
        correct: 1,
        explanation: 'Set slippage too low — swap fails. Too high — you might get a worse price. 0.5% is standard for liquid pairs.',
      },
      {
        type: 'quiz',
        question: 'What is price impact in a swap?',
        options: ['The gas fee', 'How much your trade shifts the pool\'s price — larger trades cause more impact', 'The exchange rate', 'Slippage'],
        correct: 1,
        explanation: 'Large trades relative to pool size move prices significantly. Split large trades to reduce impact.',
      },
      {
        type: 'quiz',
        question: 'What is a liquidity pool?',
        options: ['A savings account', 'A smart contract holding two tokens that traders swap against, funded by liquidity providers', 'A validator node', 'A type of NFT'],
        correct: 1,
        explanation: 'Liquidity pools are the backbone of DeFi — they replace traditional market makers with smart contracts.',
      },
      {
        type: 'quiz',
        question: 'What is MEV (Maximal Extractable Value) in context of swaps?',
        options: ['Maximum swap value', 'Profit validators/bots extract by reordering, inserting, or censoring transactions — can front-run your swaps', 'Exchange profit', 'Liquidity provider reward'],
        correct: 1,
        explanation: 'MEV bots can sandwich your swap — buying before and selling after to extract value. Jupiter has MEV protection.',
      },
      {
        type: 'quiz',
        question: 'What is a "limit order" vs a "market order" in DeFi?',
        options: ['Same thing', 'Market order swaps immediately at current price; limit order executes only when price reaches your target', 'Limit orders are faster', 'Market orders are safer'],
        correct: 1,
        explanation: 'Jupiter supports limit orders — useful for buying dips or selling at targets without monitoring price constantly.',
      },
      {
        type: 'quiz',
        question: 'Why might a swap fail with "insufficient funds for rent"?',
        options: ['You\'re out of USDC', 'Creating a new token account requires a small SOL rent deposit — you need slightly more SOL than just gas', 'The DEX is down', 'Your slippage is too high'],
        correct: 1,
        explanation: 'First time receiving a new token requires creating an Associated Token Account — costs ~0.002 SOL rent.',
      },
    ],
  },
  {
    id: 6,
    title: 'What is Staking?',
    emoji: '💎',
    color: '#FF4D94',
    xp: 200,
    difficulty: 'Intermediate',
    timeMin: 10,
    description: 'Earn passive SOL rewards by securing the network',
    steps: [
      {
        type: 'info',
        icon: '💎',
        text: 'Staking means delegating your SOL to a validator. The validator uses your stake to participate in consensus. In return, you earn ~7% APY in new SOL — paid automatically every epoch (~2.5 days).',
      },
      {
        type: 'info',
        icon: '🏦',
        text: 'Liquid staking lets you stake while staying liquid. You deposit SOL and receive mSOL (Marinade) or jitoSOL (Jito) — tokens that grow in value as staking rewards accrue. You can use these in DeFi while still earning staking yield.',
      },
      {
        type: 'info',
        icon: '⚠️',
        text: 'Choosing a good validator matters. Look for: low commission (0-10%), high uptime (99%+), and contribution to decentralization. Avoid validators with >10% of total stake — concentration is a risk.',
      },
      {
        type: 'quiz',
        question: 'What is an "epoch" in Solana staking?',
        options: ['A type of token', 'A period of approximately 2-3 days after which staking rewards are distributed and validator performance is evaluated', 'A block', 'A governance vote'],
        correct: 1,
        explanation: 'Solana epochs last ~432,000 slots (~2.5 days). Staking rewards are calculated and paid at epoch boundaries.',
      },
      {
        type: 'quiz',
        question: 'What is "validator commission" in staking?',
        options: ['Tax you pay to Solana', 'The percentage of staking rewards a validator keeps before passing the rest to delegators', 'A staking fee', 'APY rate'],
        correct: 1,
        explanation: 'A 5% commission validator keeps 5% of rewards earned with your stake. Lower is better for delegators.',
      },
      {
        type: 'quiz',
        question: 'What is the "warm-up period" for new stake?',
        options: ['Time to heat your hardware wallet', '1-2 epochs (up to ~5 days) before newly staked SOL starts earning rewards', 'Cooldown after unstaking', 'Time to find a validator'],
        correct: 1,
        explanation: 'New delegations don\'t earn rewards immediately — they activate at the next epoch boundary.',
      },
      {
        type: 'quiz',
        question: 'What is the risk of staking with a single validator?',
        options: ['No risk', 'If the validator is slashed for misbehavior or goes offline, you could lose rewards or stake', 'You earn less APY', 'Longer warm-up period'],
        correct: 1,
        explanation: 'Diversifying across multiple validators reduces concentration risk and supports network decentralization.',
      },
      {
        type: 'quiz',
        question: 'What is mSOL (Marinade)?',
        options: ['A meme token', 'A liquid staking token that represents staked SOL + accrued rewards, usable in DeFi', 'A governance token', 'A stablecoin'],
        correct: 1,
        explanation: 'mSOL lets you stake SOL while keeping liquidity — 1 mSOL is always worth more than 1 SOL due to accrued rewards.',
      },
      {
        type: 'quiz',
        question: 'What is "slashing" in Proof of Stake?',
        options: ['Burning tokens manually', 'Penalty where a validator loses a portion of staked funds for provably malicious behavior', 'Selling your stake', 'A DeFi liquidation'],
        correct: 1,
        explanation: 'Solana currently does not implement slashing, but it\'s planned — validators caught double-voting would lose stake.',
      },
      {
        type: 'quiz',
        question: 'What APY can you realistically expect from native SOL staking?',
        options: ['0.5-1%', '2-4%', '6-8%', '20-50%'],
        correct: 2,
        explanation: 'SOL staking currently yields around 6-8% APY — attractive passive income with relatively low risk.',
      },
    ],
  },
  {
    id: 7,
    title: 'What are NFTs?',
    emoji: '🎨',
    color: '#FF6B35',
    xp: 200,
    difficulty: 'Intermediate',
    timeMin: 10,
    description: 'Digital ownership and collectibles on Solana',
    steps: [
      {
        type: 'info',
        icon: '🎨',
        text: 'NFT = Non-Fungible Token. Unlike SOL (where every SOL is identical), each NFT is unique. Ownership is recorded on-chain — no company can take it from you.',
      },
      {
        type: 'info',
        icon: '🌿',
        text: 'Solana uses compressed NFTs (cNFTs) — they store data in a Merkle tree instead of individual accounts. Minting 1 million cNFTs costs about $110 total vs $100,000+ on Ethereum.',
      },
      {
        type: 'info',
        icon: '🏪',
        text: 'NFT marketplaces like Magic Eden and Tensor let you buy, sell, and trade NFTs. Royalties (a % paid to creators on each sale) are enforced on-chain in some standards.',
      },
      {
        type: 'quiz',
        question: 'What does "non-fungible" mean?',
        options: ['Cannot be sold', 'Each token is unique and not interchangeable with another — unlike currencies where $1 = $1', 'Not on a blockchain', 'Not owned by anyone'],
        correct: 1,
        explanation: 'Fungible = interchangeable (SOL, USDC). Non-fungible = unique (NFTs, tickets, deeds).',
      },
      {
        type: 'quiz',
        question: 'What is the Metaplex standard?',
        options: ['An Ethereum NFT standard', 'Solana\'s primary NFT standard — defines metadata, royalties, and collection structure', 'A wallet type', 'A DeFi protocol'],
        correct: 1,
        explanation: 'Metaplex created the token metadata standard that nearly all Solana NFTs use.',
      },
      {
        type: 'quiz',
        question: 'Where is NFT image data typically stored?',
        options: ['On the blockchain itself', 'Usually on IPFS, Arweave, or other decentralized storage — the blockchain stores a link to the metadata', 'On the artist\'s computer', 'In the wallet'],
        correct: 1,
        explanation: 'Storing images on-chain is too expensive. The NFT contains a URI pointing to off-chain metadata — Arweave is preferred for permanence.',
      },
      {
        type: 'quiz',
        question: 'What is a "compressed NFT" (cNFT) and why does it matter?',
        options: ['A low-quality image NFT', 'An NFT stored in a Merkle tree — costs ~0.000005 SOL to mint vs ~0.012 SOL for regular NFTs', 'A fractional NFT', 'An NFT on a sidechain'],
        correct: 1,
        explanation: 'cNFTs make mass distribution possible — perfect for game items, badges, and airdrops at near-zero cost.',
      },
      {
        type: 'quiz',
        question: 'What is "royalty enforcement" in NFTs?',
        options: ['Tax on NFT ownership', 'On-chain mechanism ensuring creators receive a % of every secondary sale automatically', 'Minting fee', 'A type of burn'],
        correct: 1,
        explanation: 'Royalty enforcement has been controversial — some marketplaces bypassed it. New standards aim to enforce it programmatically.',
      },
      {
        type: 'quiz',
        question: 'What is an NFT "floor price"?',
        options: ['The minimum price to mint', 'The lowest listed price in a collection — used as a benchmark for collection value', 'The creator\'s royalty', 'The gas fee to buy'],
        correct: 1,
        explanation: 'Floor price is the cheapest way to enter a collection. It\'s the most-watched metric for NFT collection health.',
      },
      {
        type: 'quiz',
        question: 'What is "wash trading" in NFT markets?',
        options: ['Cleaning NFT metadata', 'Artificially inflating volume/price by trading an NFT between wallets you control', 'A legitimate trading strategy', 'Burning low-value NFTs'],
        correct: 1,
        explanation: 'Wash trading creates fake demand signals. Watch for suspiciously high volume with few unique traders.',
      },
    ],
  },
  {
    id: 8,
    title: 'DeFi Basics',
    emoji: '🏦',
    color: '#14F195',
    xp: 250,
    difficulty: 'Intermediate',
    timeMin: 15,
    description: 'Lending, liquidity pools, and yield strategies',
    steps: [
      {
        type: 'info',
        icon: '🏦',
        text: 'DeFi (Decentralized Finance) replaces banks with smart contracts. You can lend, borrow, earn yield, and trade 24/7 — no KYC, no account approval, no business hours.',
      },
      {
        type: 'info',
        icon: '💧',
        text: 'Liquidity providers (LPs) deposit two tokens into a pool (e.g. SOL/USDC). Traders swap against this pool, and LPs earn a % of every trade. Risk: impermanent loss if token prices diverge significantly.',
      },
      {
        type: 'info',
        icon: '📈',
        text: 'Lending protocols like Kamino let you deposit tokens to earn interest, or borrow against your crypto without selling it. Health factor = safety of your loan. Below 1 = liquidation.',
      },
      {
        type: 'quiz',
        question: 'What is impermanent loss (IL)?',
        options: ['A permanent loss from hacks', 'The opportunity cost LPs face when token prices diverge — you would have been better off just holding', 'Gas fees', 'A failed transaction'],
        correct: 1,
        explanation: 'IL is called "impermanent" because it disappears if prices return to entry ratio. But if you withdraw while prices are diverged, the loss is realized.',
      },
      {
        type: 'quiz',
        question: 'What is a "health factor" in lending protocols?',
        options: ['Protocol uptime', 'A ratio showing how safe your loan is — below 1.0 triggers liquidation of your collateral', 'Your credit score', 'APY rate'],
        correct: 1,
        explanation: 'Keep health factor well above 1.0 (ideally 1.5+) to avoid liquidation during price swings.',
      },
      {
        type: 'quiz',
        question: 'What is "over-collateralization" in DeFi lending?',
        options: ['Borrowing more than you deposit', 'Depositing more value than you borrow — e.g. deposit $150 SOL to borrow $100 USDC', 'A type of liquidation', 'Zero-interest borrowing'],
        correct: 1,
        explanation: 'Most DeFi loans require over-collateralization since there\'s no credit system — your collateral is the guarantee.',
      },
      {
        type: 'quiz',
        question: 'What is a "flash loan"?',
        options: ['A fast bank loan', 'An uncollateralized loan that must be borrowed and repaid within the same transaction block', 'A microloan', 'A stablecoin mint'],
        correct: 1,
        explanation: 'Flash loans enable arbitrage, liquidations, and collateral swaps with zero capital — if not repaid in the same tx, the whole thing reverts.',
      },
      {
        type: 'quiz',
        question: 'What is "TVL" (Total Value Locked)?',
        options: ['Total transactions per day', 'The total value of assets deposited in a DeFi protocol — key metric for protocol health', 'Token volume traded', 'Validator count'],
        correct: 1,
        explanation: 'Higher TVL generally indicates more trust and usage, but can also concentrate systemic risk.',
      },
      {
        type: 'quiz',
        question: 'What is a "rug pull" in DeFi?',
        options: ['A smart contract bug', 'When developers drain liquidity or treasury and abandon the project, leaving investors with worthless tokens', 'A governance vote gone wrong', 'An impermanent loss event'],
        correct: 1,
        explanation: 'Red flags: anonymous team, no audit, locked liquidity expiring soon, unrealistic APYs.',
      },
      {
        type: 'quiz',
        question: 'What does "yield farming" mean?',
        options: ['Growing physical crops with crypto', 'Actively moving assets across protocols to maximize returns from interest + liquidity rewards + token incentives', 'Staking SOL', 'Minting NFTs'],
        correct: 1,
        explanation: 'Yield farmers compound multiple reward streams — but high yields usually mean high risk or token inflation.',
      },
    ],
  },
  {
    id: 9,
    title: 'Scam Recognition',
    emoji: '🛡️',
    color: '#FF4444',
    xp: 200,
    difficulty: 'Intermediate',
    timeMin: 10,
    description: 'Protect yourself from crypto scams',
    steps: [
      {
        type: 'info',
        icon: '🎣',
        text: 'Phishing is the #1 crypto attack. Fake websites, fake Discord DMs, fake Twitter accounts — all designed to get your seed phrase or trick you into signing a malicious transaction.',
      },
      {
        type: 'info',
        icon: '🧠',
        text: 'Social engineering attacks exploit psychology, not technology. "Your wallet is compromised — verify now." "Limited time airdrop — connect to claim." "I\'m Solana support — send 1 SOL to verify your wallet." All scams.',
      },
      {
        type: 'info',
        icon: '✅',
        text: 'Before signing ANY transaction: check the dApp URL, read what the transaction does, verify the contract address, and use a transaction simulator (like Blowfish built into Seeker) to preview outcomes.',
      },
      {
        type: 'quiz',
        question: 'What is a "wallet drainer"?',
        options: ['A low battery warning', 'A malicious smart contract that transfers all your tokens/NFTs to an attacker when you sign', 'A slow transaction', 'A DeFi protocol'],
        correct: 1,
        explanation: 'Drainers are hidden in fake NFT mints, fake airdrops, and phishing sites. One signature can empty your wallet.',
      },
      {
        type: 'quiz',
        question: 'You receive a DM: "Congrats! You\'ve been selected for a 1000 SOL airdrop. Connect your wallet to claim." What is this?',
        options: ['A real airdrop — claim it!', 'A wallet drainer scam — legitimate airdrops don\'t require connecting to random links via DM', 'A Solana Foundation promotion', 'A test transaction'],
        correct: 1,
        explanation: 'Unsolicited DM airdrops are almost always drainer attacks. Verify through official project channels only.',
      },
      {
        type: 'quiz',
        question: 'What is a "honeypot" token?',
        options: ['A sweet reward token', 'A token you can buy but not sell — smart contract blocks all sells except the deployer\'s', 'A governance token', 'A stablecoin'],
        correct: 1,
        explanation: 'Honeypots look attractive (fast price pump) but trap buyers. Always check if a token can be sold before buying.',
      },
      {
        type: 'quiz',
        question: 'What does a legitimate Solana transaction approval show?',
        options: ['Just "confirm" with no details', 'The specific instructions, accounts affected, token amounts, and estimated outcomes', 'Your seed phrase for verification', 'A captcha'],
        correct: 1,
        explanation: 'Wallets like Phantom and the Seeker Seed Vault show transaction simulation — if you can\'t see what it does, don\'t sign.',
      },
      {
        type: 'quiz',
        question: 'What is "address poisoning"?',
        options: ['Corrupting a smart contract', 'Sending tiny transactions from an address that looks like one you\'ve used — hoping you copy-paste the wrong address', 'A DNS attack', 'A phishing email'],
        correct: 1,
        explanation: 'Always verify full addresses, not just first/last characters. Address poisoning exploits the habit of checking only start/end.',
      },
      {
        type: 'quiz',
        question: 'What is a "pig butchering" scam?',
        options: ['A meat market NFT', 'Long-term relationship scam where fraudsters build trust over weeks/months before convincing victims to invest in fake platforms', 'A DeFi exploit', 'A token name'],
        correct: 1,
        explanation: 'These scams often start on dating apps or social media. The "investment platform" is fake — you can deposit but never withdraw.',
      },
      {
        type: 'quiz',
        question: 'Best practice before interacting with any new dApp?',
        options: ['Just try it with your main wallet', 'Verify official links, check audits, use a burner wallet first, simulate the transaction, start with small amounts', 'Ask in Telegram', 'Trust verified Twitter accounts'],
        correct: 1,
        explanation: 'A layered approach: verify → audit → burner wallet → simulate → small test → then full amount.',
      },
    ],
  },
  {
    id: 10,
    title: 'Advanced DeFi',
    emoji: '🚀',
    color: '#9945FF',
    xp: 500,
    difficulty: 'Advanced',
    timeMin: 25,
    description: 'Advanced yield strategies and DeFi mechanics',
    steps: [
      {
        type: 'info',
        icon: '🔄',
        text: 'Looping (recursive lending) lets you deposit SOL, borrow USDC, buy more SOL, deposit again — amplifying both yield and risk. A 10% SOL price drop becomes a 30%+ loss at 3x leverage.',
      },
      {
        type: 'info',
        icon: '⚖️',
        text: 'Delta-neutral strategies aim for zero price exposure while capturing yield. Example: long spot SOL + short SOL perpetual futures = earn staking yield + funding rate, no price risk.',
      },
      {
        type: 'info',
        icon: '🏗️',
        text: 'Concentrated liquidity (CLMM) lets LPs focus capital in a specific price range for much higher fee earnings — but requires active management. If price moves outside your range, you stop earning fees.',
      },
      {
        type: 'quiz',
        question: 'What is a CLMM (Concentrated Liquidity Market Maker)?',
        options: ['A type of NFT collection', 'A liquidity model where LPs set specific price ranges to concentrate capital for higher capital efficiency', 'A cross-chain bridge', 'A lending protocol'],
        correct: 1,
        explanation: 'CLMMs (used in Orca Whirlpools, Raydium CLMM) can earn 10-100x more fees per dollar than traditional AMMs — but require active management.',
      },
      {
        type: 'quiz',
        question: 'What is a "perpetual future" (perp) in DeFi?',
        options: ['A token that never expires', 'A leveraged derivative contract with no expiry, where funding rates balance longs vs shorts', 'An infinite staking vault', 'A cross-chain token'],
        correct: 1,
        explanation: 'Perps let you go long or short with leverage. Platforms like Drift and Jupiter Perps run fully on-chain.',
      },
      {
        type: 'quiz',
        question: 'What is a "funding rate" in perpetual futures?',
        options: ['Development grant', 'Periodic payment between longs and shorts to keep the perp price near spot — positive rate means longs pay shorts', 'Staking APY', 'Bridge fee'],
        correct: 1,
        explanation: 'High positive funding = longs pay shorts = bullish sentiment. You can earn funding rates by being short during bull markets.',
      },
      {
        type: 'quiz',
        question: 'What is liquidation cascade risk in leveraged DeFi?',
        options: ['Multiple waterfalls in code', 'When price drops trigger liquidations → more selling → more liquidations → accelerated crash', 'A governance vote', 'Slow network issue'],
        correct: 1,
        explanation: 'March 2020 and Luna collapse showed how leveraged positions create cascading liquidations that amplify price crashes.',
      },
      {
        type: 'quiz',
        question: 'What is a "vault strategy" in yield aggregators like Kamino?',
        options: ['A place to store NFTs', 'Automated strategy that compounds rewards, rebalances positions, and harvests fees without manual intervention', 'A cold storage solution', 'A governance mechanism'],
        correct: 1,
        explanation: 'Yield vaults automate complex strategies — depositors get a receipt token representing their growing share.',
      },
      {
        type: 'quiz',
        question: 'What is the risk of smart contract composability ("money legos")?',
        options: ['No risk — more integrations = safer', 'A bug in one protocol can cascade through all integrated protocols — a single exploit can drain multiple systems', 'Only affects small protocols', 'Only relevant on Ethereum'],
        correct: 1,
        explanation: 'DeFi composability creates systemic risk. The Mango Markets exploit in 2022 showed how one vulnerability can drain $100M+.',
      },
      {
        type: 'quiz',
        question: 'What is a DAO treasury and how is it governed?',
        options: ['A bank account', 'Community-controlled funds managed via on-chain governance votes using governance tokens', 'The developer\'s wallet', 'A multisig with fixed signers'],
        correct: 1,
        explanation: 'DAOs use token-weighted voting to decide on treasury spending, protocol upgrades, and parameter changes — though governance attacks are a real threat.',
      },
      {
        type: 'quiz',
        question: 'What is "points meta" in DeFi and why is it controversial?',
        options: ['A new DeFi standard', 'Protocols issuing off-chain points promising future airdrops to attract TVL — controversial because points can be worthless', 'A governance system', 'A trading strategy'],
        correct: 1,
        explanation: 'Points systems bootstrap liquidity but create mercenary capital that leaves post-airdrop. Sustainability depends on real product value.',
      },
    ],
  },
];

export const BADGE_DATA = [
  { id: 1, name: 'Solana Pioneer', desc: 'Complete the Fundamentals module', icon: '🔵', moduleId: 2 },
  { id: 2, name: '7-Day Streak', desc: 'Maintain a 7 day learning streak', icon: '🔥', moduleId: null },
  { id: 3, name: 'Security Guru', desc: 'Complete the Wallet Security module', icon: '🛡️', moduleId: 9 },
  { id: 4, name: 'Quiz Master', desc: 'Score 100% on 5 quizzes', icon: '🧠', moduleId: null },
  { id: 5, name: 'DeFi Explorer', desc: 'Complete the DeFi module', icon: '🏦', moduleId: 8 },
  { id: 6, name: 'Early Adopter', desc: 'Join before 2026', icon: '⭐', moduleId: null },
];